baseURL: http://localhost:1313/
#languageCode: en-us
title: Thomas' Portfolio
theme: ["PaperMod"]
#add module
module:
  imports:
    path: "github.com/mfg92/hugo-shortcode-gallery"



markup:
  goldmark:
    renderer:
      unsafe: true



assets: 
  - disableHLJS: true


params:
  env: production
  defaultTheme: auto
  profileMode:
    enabled: true
    title: Thomas Bolf
    subtitle: Mathematics and Computer Science Student
    imageUrl: "images/image.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Me!

  homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: Welcome to my blog! I'm a student at the University of Minnesota studying Mathematics and Computer Science. I'm passionate about learning and sharing knowledge. I'm always looking for new opportunities to learn and grow. I'm currently working on a few projects, so stay tuned for updates! Feel free to reach out to me on social media or via email. I'd love to hear from you!


  socialIcons:
    - name: github
      url: https://github.com/thomasbolf
    - name: LinkedIn
      url: https://www.linkedin.com/in/thomas-bolf-5a54a6259/
    - name: goodreads
      url: https://www.goodreads.com/user/show/175463450-thomas-bolf
    - name: strava
      url: https://www.strava.com/athletes/131990767

menu:
  main:
    - identifier: party
      name: ğŸ‰
      url: party.html
      weight: 10


    - identifier: gallery
      name: Gallery 
      url: gallery/
      weight: 25
    - identifier: chase
      name: Internship Experience
      url: chase/
      weight: 30
    - identifier: publication
      name: Research
      url: publication/
      weight: 35
    - identifier: skills
      name: Skills
      url: skills/
      weight: 40
    - identifier: projects
      name: Projects
      url: projects/
      weight: 45


  ##make cover images smaller
    # buttons:
    #   - name:  ğŸ–¥ï¸ My Work ğŸ”¨  
    #     url: works/
    #   - name: ğŸ“” Notebooks âœï¸ 
    #     url: notebooks/
    #   - name: ğŸ“¸ Gallery ğŸ“¸ 
    #     url: gallery/



# menu:
#   main:
#     - identifer: Home
#       name: Home
#       url: /
#       weight: 10
