baseURL: http://localhost:1313/
#languageCode: en-us
title: Thomas' Portfolio
theme: ["PaperMod"]

markup:
  goldmark:
    renderer:
      unsafe: true



assets: 
  - disableHLJS: true


params:
  env: production
  defaultTheme: auto
  profileMode:
    enabled: true
    title: Thomas Bolf
    subtitle: Mathematics and Computer Science Student
    imageUrl: "image.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Me!
    buttons:
      - name:  ğŸ–¥ï¸ My Work ğŸ”¨  
        url: works/
      - name: ğŸ“” Notebooks âœï¸ 
        url: notebooks/
      - name: ğŸ“¸ Gallery ğŸ“¸ 
        url: gallery/


  socialIcons:
    - name: github
      url: https://github.com/thomasbolf
    - name: LinkedIn
      url: https://www.linkedin.com/in/thomas-bolf-5a54a6259/
    - name: goodreads
      url: https://www.goodreads.com/user/show/175463450-thomas-bolf

menu:
  main:
    - identifier: Home
      name: Fun Fact
      url: /dog
      weight: 10
    - identifier: party
      name: ğŸ‰
      url: /party/party
      weight: 10
  ##make cover images smaller




# menu:
#   main:
#     - identifer: Home
#       name: Home
#       url: /
#       weight: 10
